CREATE TABLE Person (
	IDPerson INTEGER IDENTITY PRIMARY KEY,
	FirstName CHAR(50) NOT NULL, 
	LastName CHAR(100) NOT NULL,
	Login CHAR(30) NOT NULL,
	Password CHAR(15) NOT NULL,
	IsStaff BIT ,
	IsAdmin BIT
);

CREATE TABLE TypeOfRoom (
	IDTypeOfRoom INTEGER IDENTITY PRIMARY KEY,
	Information CHAR(50) NOT NULL, 
	NumberOfPerson CHAR(100) NOT NULL
)

CREATE TABLE Room(
	IDRoom INTEGER IDENTITY PRIMARY KEY,
	TypeOfRoom_FK Integer,
	NumberOfRoom INTEGER,
	FloorNr INTEGER,
	FOREIGN KEY(TypeOfRoom_FK) REFERENCES TypeOfRoom(IDTypeOfRoom)
);

CREATE TABLE StatusOfReservation(
	IDStatus INTEGER IDENTITY PRIMARY KEY,
	Status CHAR(100)
);

CREATE TABLE Reservation (
	IDReservation INTEGER IDENTITY PRIMARY KEY,
	CheckIn DATETIME NOT NULL, 
	CheckOut DATETIME NOT NULL,
	Room_FK INTEGER ,
	Status_FK INTEGER,
	Cost FLOAT,
	Person_FK INTEGER,
	FOREIGN KEY(Person_FK) REFERENCES Person(IDPerson),
	FOREIGN KEY(Room_FK) REFERENCES Room(IDRoom),
	FOREIGN KEY(Status_FK) REFERENCES StatusOfReservation(IDStatus)
)

