//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BookingSystem.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Reservation
    {
        public int IDReservation { get; set; }
        [Display(Name = "Check-in")]
        [DisplayFormat(ApplyFormatInEditMode = true, DataFormatString = "{0:dd/MM/yyyy}")]
        public System.DateTime CheckIn { get; set; }
        [Display(Name = "Check-out")]
        [DisplayFormat(ApplyFormatInEditMode = true, DataFormatString = "{0:dd/MM/yyyy}")]
        public System.DateTime CheckOut { get; set; }
        public Nullable<int> Room_FK { get; set; }
        public Nullable<int> Status_FK { get; set; }
        public Nullable<double> Cost { get; set; }
        public Nullable<int> Person_FK { get; set; }
    
        public virtual Person Person { get; set; }
        [Display(Name = "Room")]
        [DisplayFormat(ApplyFormatInEditMode = true, DataFormatString = "{0:dd/MM/yyyy}")]
        public virtual Room Room { get; set; }
        public virtual StatusOfReservation StatusOfReservation { get; set; }
    }
}
